Case:
Create numpy array from your inputted full name in the form of numbers based on order in alphabets. You can use this translater to change from alphabet to number: 
```py
letter_to_word = {'a': 1, 'c': 3, 'b': 2, 'e': 5, 'd': 4, 'g': 7, 'f': 6, 'i': 9, 'h': 8, 'k': 11, 'j': 10, 'm': 13, 'l': 12, 'o': 15, 'n': 14, 'q': 17, 'p': 16, 's': 19, 'r': 18, 'u': 21, 't': 20, 'w': 23, 'v': 22, 'y': 25, 'x': 24, 'z': 26}
```
Also add repetition on the number based on your inputted number.
Example:
inputted full name = 'Jenny'<br>
repeated = 4 times<br>
result:<br>
```
[[10  5 14 14 25]
 [10  5 14 14 25]
 [10  5 14 14 25]
 [10  5 14 14 25]]
```

In [2]:
import numpy as np

In [27]:
name = "william"
number_1 = []
for x in name:
    number = ord(x)-96
    number_1.append(number)
print (number_1)

a = np.full ((4,7), [number_1],dtype=int)
print (a)

[23, 9, 12, 12, 9, 1, 13]
[[23  9 12 12  9  1 13]
 [23  9 12 12  9  1 13]
 [23  9 12 12  9  1 13]
 [23  9 12 12  9  1 13]]
